### Programmers
GET http://localhost:9080/programming-magic/api/programmer
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

### Programmer
GET http://localhost:9080/programming-magic/api/programmer/{{programmerUuid}}
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

### Programmer - not existing
GET http://localhost:9080/programming-magic/api/programmer/12345678-552d-4fc2-8e64-644044d1dcb9
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

### Programmer's portrait
GET http://localhost:9080/programming-magic/api/programmer/{{programmerUuid}}/portrait
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

### Delete portrait
DELETE http://localhost:9080/programming-magic/api/programmer/{{programmerUuid}}/portrait
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

### Put portrait
PUT http://localhost:9080/programming-magic/api/programmer/{{programmerUuid}}/portrait
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==
Content-Type: multipart/form-data; boundary=myboundary

--myboundary
Content-Disposition: form-data; name="portrait"; filename="shayne.png"

< ./src/main/resources/pl/edu/pg/eti/kask/s180171/programmingmagic/portrait/shayne.png
--myboundary--

### Add programmer
POST http://localhost:9080/programming-magic/api/programmer
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==
Content-Type: application/json

{
  "name": "Shayne",
  "title": "Shayne Topp",
  "birthday": "1991-09-14",
  "level": "JUNIOR"
}

### Update programmer
PATCH http://localhost:9080/programming-magic/api/programmer/{{programmerUuid}}
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==
Content-Type: application/json

{
  "name": "Shayne",
  "title": "GOLLLLIIATHH",
  "birthday": "1991-09-14",
  "level": "MASTER"
}

### Delete programmer
DELETE http://localhost:9080/programming-magic/api/programmer/{{programmerUuid}}

### Add programmer's program
POST http://localhost:9080/programming-magic/api/programmer/{{programmerUuid}}/program
Content-Type: application/json

{
  "name": "testowy program",
  "description": "testowy opis",
  "code": "testowy kod",
  "dateOfCreation": "2019-01-01"
}

### Programmer's programs
GET http://localhost:9080/programming-magic/api/programmer/{{programmerUuid}}/program

### Programmer's program
GET http://localhost:9080/programming-magic/api/program/{{programUuid}}

### Update programmer's program

PATCH http://localhost:9080/programming-magic/api/program/{{programUuid}}
Content-Type: application/json

{
  "name": "testowy AAAAAAm",
  "description": "tAAAA opis",
  "code": "tesBBBBBBBC+++od",
  "dateOfCreation": "2019-01-01"
}

### Delete programmer's program

DELETE http://localhost:9080/programming-magic/api/program/{{programUuid}}

### All programs
GET http://localhost:9080/programming-magic/api/program